### ISSUE TITLE
Confusing use of "Event"/"Filter" naming

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/FEV#154]
When you first hit http://test.wim.usgs.gov/FEV/ a modal pops up and you select an "event" to view.

After selecting an event you are taken to the map with that event's information displayed. If you want to change to a different event you click "FILTERS" in the left sidebar. In that field both names(event,filters) are used.

Took me a little bit realize I needed to go to Filters in order to change the event being viewed. Assumed you'd have to enter http://test.wim.usgs.gov/FEV/ in the browser again and select a different event.

Will there one day be additional filters? or will you be able to select more than 1? If not, then would calling it just "Event" prevent some potential confusion?

**Comment by BlakeDraper** [comment]
Event is one of the filters available, but it it also a required filter. The load screen only prompts for event choice because the user cannot see any data unless they first choose an event. We don't intend to add all the filters to the load window because that would be too much to decide before you have even seen the data. So "Filters" is the set of choices by which you can narrow the data view, and "Event" is just one of those choices, or 'filters'.

STN and by extension FEV, is an event-centric database - meaning all the data that the public is permitted to see must be based on an event - without an event choice there really is no data to show. As for showing multiple events at once, we decided against that for v2.0 for a number of reasons, mostly having to do with UI challenges. A future version may support multiple event selection. 

One easy way we could make this a little more obvious would be to make the Filters accordion panel open on load so people can see right away that the Event is a filter, and that they can change it, along with other filters, by clicking that blue button.

**Comment by BlakeDraper** [comment]
Made that panel open by default with PR #161
