### ISSUE TITLE
Rename Storm Tide Sensor to Water Level Sensor

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/FEV#211]
Rename "Storm Tide Sensor" in FEV to "Water Level Sensor" because these are sometimes deployed inland to measure riverine response.

**Comment by lprivette** [comment]
Need to double check this change with Athena

**Comment by lprivette** [comment]
"Water Level Sensor"

discussed on stn user group call

**Comment by 09Kathy** [comment]
Should we also remove or change the explanation of storm tide in the FAQ? We could say something like 'What is water level?' 'In FEV, water level refers to the low-passed filtered water level, which is caused by the combination of....' ?

3. What is storm tide (low-pass filtered water level?)
The storm tide is defined as the water level caused by the combination of the astronomical tide and storm surge. The low-pass filter is a tool used to remove wave noise from the data. This provides a more accurate representation of the storm tide water level at the site.

**Comment by lprivette** [comment]
Are you wanting to break FAQ 3 into 2 FAQs? Sorry a little confused at what you're asking here.

That text was just written and approved by the STN User Group. IF it's confusing, I'd suggest posting your question to Laura and Robert in the Teams channel. You can see the history for the text on September 17 of that groups chat.

**Comment by 09Kathy** [comment]
I'm just wondering if the explanation of storm tide was included in the FAQ so that it corresponds with the label in the legend. Since we're changing the label in the legend, I'm wondering if that means we also need to change the FAQ. If that's not the case and the storm tide explanation is included not because of our legend/markers, than it makes sense to leave it be.

**Comment by lprivette** [comment]
ah yes, I see what you mean.

I think we leave it as is. 'Storm tide' in q 3 is referring to the the actual event of storm tide and how it's measured, not the sensor right? And the same for q 2. I agree it is still a little confusing.

I still think you can ask the STN User group about this. "Since we've changed the name of the Storm Tide Sensor, does this not make these FAQs confusing?" kind of thing.
