### ISSUE TITLE
Update FAQ 3

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/FEV#350]
Athena provided the text

**Comment by jprokopec** [comment]
Another Update to FAQ

1. What is the FEV?

The [Flood Event Viewer](https://stn.wim.usgs.gov/FEV/) or FEV was created by the USGS to provide public access to coordinated, short snippets (lengths) of coastal and riverine water-level and highwater mark records corresponding to major storms or other short-term events. Long-term records for permanent USGS streamgages are available at the USGS [National Water Information System](https://waterdata.usgs.gov/nwis) (NWIS).




2. What is total water level (unfiltered water level)?

The total water level or unfiltered water level is the water surface measured and recorded by the sensor. During a coastal storm event, the total water level is defined as the combination of the astronomical tide, storm surge, and waves.




3.  What is storm tide (low-pass filtered water level)?

The storm tide is defined as the water level caused by the combination of the astronomical tide and storm surge.




4. How does the USGS filter storm tide data?

The USGS uses the Butterworth Filter (low-pass filter) to attenuate high frequencies in order to remove the components of wave setup and runup to estimate the storm tide at the site.  To learn more about the Butterworth Filter utilized by the USGS, please visit [WaveLab](https://code.usgs.gov/wavelab/wavelab/-/blob/master/README.md). 




The smoothness of the low-pass filtered line will depend on the sensor type (water level or wave sensor), on the location of where the sensor was deployed, the intensity of the storm, filter type, and filter period.  




Listed below is the history of the use of the WaveLab Butterworth Filter utilized by the USGS: 

From 2005 - 2015, the USGS did not apply a low-pass filter to remove the components of wave setup and runup. 
From 2015-2020, the USGS used the Butterworth Filter with various filtering periods.   
Starting in 2021, with Hurricane Henri, the USGS standardized the filtering period to 6-minutes. 




5. Who do I reach out to for questions about the data?

You can submit any data questions via our Answers form on the USGS website: https://answers.usgs.gov/.

For the 'Topic' field please select 'Water'.




6. How should I reference your data in my publication?

Please reference the USGS Flood Event Viewer in all publications that use data from this system.

Template citation:
U.S. Geological Survey, [year], Short-Term Network Data Portal, accessed on [full-date], at http://water.usgs.gov/floods/FEV/.

**Comment by lprivette** [comment]
Done and deployed to FEV
